management:
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /
      path-mapping:
        prometheus: /metrics

resilience4j:
    circuitbreaker:
        backends:
            nambawan:
                ringBufferSizeInClosedState: 100
                ringBufferSizeInHalfOpenState: 10
                waitInterval: 10000
                failureRateThreshold: 50
                recordFailurePredicate: com.example.resilience4jkotlin.predicate.NambawanCircuitBreakerPredicate
                recordExceptions:
                    - org.springframework.web.client.HttpServerErrorException
                ignoreExceptions:
                    - org.springframework.web.client.HttpClientErrorException