management:
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /
      path-mapping:
        prometheus: /metrics
#  metrics:
#    distribution:
#      percentiles-histogram:
#        http.server.requests: true
#      sla:
#        http.server.requests: 300ms
#  health:
#    rabbit:
#      enabled: false

resilience4j.circuitbreaker:
    backends:
        nambawan:
            ringBufferSizeInClosedState: 6
            ringBufferSizeInHalfOpenState: 3
            waitInterval: 7000
            failureRateThreshold: 50